[settings]
show_hints = true
paper_size = "A4"
language = "Bulgarian"
fonts_path = "./assets/fonts"
font = "TimesNewRoman"
output = "output.pdf"

[header]
title = "Test Header"

[[questions]]
question = "Select the correct statement"
correct = []
incorrect = ["New Answer", "New Answer", "New Answer", "New Answer", "New Answer", "New Answer"]
points = 4
