[settings]
show_hints = true
paper_size = "A4"
language = "English"
fonts_path = "./assets/fonts"
font = "TimesNewRoman"
output = "output.pdf"

[header]
title = "Test Header"

[[questions]]
question = "New selection question"
correct = ["True"]
incorrect = ["False"]
points = 2

[[questions]]
question = "New selection question"
correct = ["True"]
incorrect = ["False"]
points = 8

[[questions]]
question = "New input question"
number_of_lines = 10
points = 1
