[settings]
show_hints = true
paper_size = "A4"
language = "Bulgarian"
fonts_path = "./assets/fonts"
font = "TimesNewRoman"
output = "out.pdf"

[header]
title = "Test of the test"

[[questions]]
question = "Is this statement true: \"PDF sucks\"?"
correct = ["yes"]
incorrect = ["no"]
points = 1

[[questions]]
question = "A longer question with selection answers!"
correct = ["yes", "ye"]
incorrect = ["no", "nah"]
points = 2

[[questions]]
question = "Why tho?"
number_of_lines = 4
points = 1

[[questions]]
question = "Lots of answers"
correct = ["yes", "ye", "yup", "yessir", "da"]
incorrect = ["no", "nah", "nope", "nosir", "ne"]
points = 2

[[questions]]
question = "XD"
correct = ["1"]
incorrect = ["2", "3"]
points = 1
