[settings]
show_hints = true
paper_size = "A4"
language = "Bulgarian"
fonts_path = "./assets/fonts"
font = "TimesNewRoman"
output = "output.pdf"
max_questions = 5
randomize_questions = false

[header]
title = "Test Header"

[[questions]]
question = "First"
correct = []
incorrect = []
points = 8

[[questions]]
question = "Second"
number_of_lines = 9
points = 8

[[questions]]
question = "Third"
correct = []
incorrect = []
points = 1

[[questions]]
question = "Fourth"
correct = []
incorrect = []
points = 1

[[questions]]
question = "Fifth"
correct = []
incorrect = []
points = 4

[[questions]]
question = "Sixth"
correct = []
incorrect = []
points = 5

[[questions]]
question = "New selection question"
correct = ["correct 1", "correct 2"]
incorrect = ["incorrect 1", "incorrect 2"]
points = 1
