[settings]
show_hints = true
paper_size = "A4"
language = "Bulgarian"
fonts_path = "./assets/fonts"
font = "TimesNewRoman"

[[questions]]
question = "Is this statement true: \"PDF sucks\"?"
correct = ["yes"]
incorrect = ["no"]

[[questions]]
question = "A longer question with selection answers!"
correct = ["yes", "ye"]
incorrect = ["no", "nah"]
points = 2

[[questions]]
question = "Why tho?"
number_of_lines = 4

[[questions]]
question = "Lots of answers"
correct = ["yes", "ye", "yup", "yessir", "da"]
incorrect = ["no", "nah", "nope", "nosir", "ne"]
points = 2
